-- Post-Deployment Script
-- Add sessions
-- INSERT INTO Sessions (Title, Description, SessionType, Level, Duration, SpeakerId)
-- VALUES 
-- ('Software Engineering 101', 'An introduction to software engineering...', 'Workshop', 'Beginner', 60, 1),
-- ('Data Science for Dummies', 'A beginner-friendly guide to data science...', 'Lecture', 'Beginner', 90, 2),
-- ('Product Management Basics', 'Learn the fundamentals of product management...', 'Workshop', 'Intermediate', 120, 3);

-- Sessions
INSERT INTO Sessions (Title, Description, SessionType, Level, Duration, SpeakerId)
VALUES
('Optimización de costos y despliegue de sitios web en GCP', 'Descubre estrategias eficientes para desplegar sitios web en Google Cloud Platform (GCP)! Exploraremos un enfoque minucioso que tiene como objetivo principal minimizar costos en la infraestructura, ofreciendo valiosas insights sobre cómo lograr una implementación eficiente y económica. Acompañame en esta sesión para obtener ideas prácticas sobre orquestación de infraestructuras en GCP y maximizar el rendimiento de tus sitios web mientras optimizas tus recursos.', 'Sesion corta', 'Principiante', 60, 1),
('Páginas multi-Idioma en Next.js en Google Cloud Run', 'Descubre cómo utilizar Next.js para crear páginas web multi-idioma eficientes y cómo desplegarlas en Google Cloud Run. Esta sesión se centra en las técnicas de internacionalización en Next.js y en las estrategias de despliegue óptimas en la nube, ofreciendo una guía práctica para desarrolladores y entusiastas de la tecnología.', 'Sesion regular', 'Intermedio', 60, 2),
('Infraestructura moderna como código con Pulumi', 'En este workshop, aprenderás los fundamentos de la infraestructura como código a través de ejercicios guiados. Te familiarizarás con Pulumi, una plataforma de infraestructura como código, donde podrás utilizar lenguajes de programación familiares para aprovisionar infraestructura en la nube de manera moderna. Aprenderás las mejores prácticas para aprovisionar, actualizar y eliminar, así como la creación de canalizaciones de infraestructura CI/CD con Github Actions.', 'Workshop', 'Intermedio', 120, 3),
('Creando un Chat Bot con .NET 8 y Azure Open IA', 'En este workshop realizaremos un Chat Bot utilizando .NET 8 y utilizaremos los servicios de Azure Open IA. Lo cual permitirá dotar a nuestro Chat Bot de la tecnología de ChatGPT. Para la parte de UI trabajaremos con Blazor en .NET 8. Prerequisitos: SDK de .NET 8 (El más reciente) Visual Studio 2022 (El más reciente) o Visual Studio Code Opcional: Una cuenta de Azure', 'Workshop', 'Avanzado', 120, 4),
('Git y GitHub para todos: Dominando Control de Versiones en todos los niveles', '¿Quieres dominar las herramientas esenciales para el desarrollo de software moderno? Únete a nuestro workshop interactivo Domina Git y GitHub. Este taller está diseñado tanto para principiantes que dan sus primeros pasos, como para desarrolladores que buscan afianzar y expandir sus habilidades. Fundamentos de Git y GitHub -Comandos básicos de Git (clone, commit, push, pull). -Creación de repositorios en GitHub, issues básicos. -Ejercicio práctico: Contribuir a un repositorio simple. Mejorando la Eficiencia con Git y GitHub -Ramificaciones y gestión de branches. -Pull requests y revisión de código básica. -Ejercicio práctico: Trabajar en un proyecto colaborativo. Estrategias Expertas y Automatización -Técnicas avanzadas de merge y rebase. -GitHub Actions y automatización de flujos de trabajo. -Ejercicio práctico: Configuración de CI/CD en un proyecto.', 'Workshop', 'Principiante', 120, 5),
('Potencia tu carrera: Guia para aumentar tu valor laboral', 'Taller Intensivo diseñado para ayudarte a potenciar tu perfil laboral en la industria tecnológica, aumentar tu valor salarial y atraer la atención de los mejores reclutadores de la industria. Este taller está especialmente diseñado para aquellos que desean destacar en su campo de especialización (aplicable a todas las áreas operativas, gerencias y Direcciones dentro de la industria del software) y maximizar su potencial en el mercado laboral. Durante el taller, abordaremos temas como la construcción de un perfil atractivo en línea, la optimización del currículum vitae y la preparación para entrevistas de trabajo de alto nivel. Además, brindaremos herramientas para identificar las fortalezas y debilidades, y proporcionaremos estrategias para ser encontrados por el algoritmo de linkedin y ser mostrado a los reclutadores.', 'Sesion corta', 'Avanzado', 60, 6),
('Hablemos de Operadores de Kubernetes', 'Muchas veces le huimos a la idea de adentrarnos al mundo de Kubernetes solo porque se ve muy complejo. Pero ¿qué pensarías si te digo que como desarrollador es mucho más sencillo aprender de Kubernetes e inclusive llegar a extenderlo para cubrir hasta los casos de uso más creativos? Si tienes curiosidad y traes tu propia computadora tendremos la oportunidad de escribir nuestros propios operadores de Kubernetes juntos.', 'Sesion corta', 'Intermedio', 60, 7),
('DevOps: Más alla de la cultura, expectativa vs realidad', 'En esta apasionante sesion, exploraremos el mundo de DevOps desde una perspectiva única: La brecha entre expectativas y realidad. Desmitificaremos la cultura DevOps a través de experiencias prácticas, destacando los desafíos reales que los profesionales enfrentan diariamente. Desde la teoría hasta la aplicación, analizaremos cómo las expectativas iniciales chocan con la realidad al integrar desarrollo y operaciones. Desglosaremos herramientas clave y casos de estudio, proporcionando una visión completa de cómo DevOps transforma la forma en que desarrollamos, entregamos y mantenemos software. Únete a esta sesión interactiva y descubre cómo superar las expectativas iniciales para abrazar la verdadera esencia de DevOps. Desde la automatización hasta la cultura, exploraremos los aspectos prácticos y desafiantes de la implementación de DevOps, ofreciendo ideas valiosas para optimizar procesos de desarrollo y operaciones. ¡Prepárate para un viaje a través de la realidad de DevOps!', 'Sesion regular', 'Avanzado', 60, 8),
('GitOps en GCP: Desplegando Aplicaciones con Argo CD y Config Connector', 'Descubre el poder de GitOps y la automatización en Google Cloud Platform (GCP) con Argo CD y Config Connector. Exploraremos cómo desplegar aplicaciones de manera eficiente, utilizando un enfoque centrado en Git para gestionar recursos en GCP. Aprende a simplificar la gestión de los recursos necesarios para ejecutar tu aplicación, todo con la eficacia de Argo CD y la integración perfecta de Config Connector en Google Kubernetes Engine (GKE).', 'Sesion corta', 'Intermedio', 60, 9),
('Visión Global de Prompt Flow y AI Studio en el uso de LLMs', 'En esta sesión utilizaremos una visión general de Prompt Flow y AI Studio, que es un conjunto de herramientas de desarrollo diseñadas para optimizar el ciclo completo de desarrollo de aplicaciones basadas en IA, específicamente en Modelos de Lenguaje de Gran Escala (LLM). Estas herramientas abarcan desde la ideación, la creación de prototipos, las pruebas, la evaluación, hasta la implementación y el monitoreo de producción. Demo: Enfoca en la demostración práctica, detallando la creación de flujos LLM y su evaluación. Objetivos de la sesion: - Comprender qué es Prompt Flow, AI Studio y para qué sirve. - Revisar buenas prácticas de ingeniería de prompts. - Revisar diferentes tipos de flujos.', 'Sesion regular', 'Intermedio', 60, 10),
('Integrando LLMs en la Nube de AWS: Un Enfoque Práctico', 'En esta sesión, se realizará una introducción a los Modelos de Lenguaje de Gran Escala (LLM) y su revolución en el procesamiento del lenguaje natural. Se explorará la integración de modelos, como los proporcionados por Hugging Face, en la infraestructura de AWS para el desarrollo y despliegue de aplicaciones de inteligencia artificial. Puntos clave de la sesión: - Eficiencia de los LLM en AWS, - Ventajas de la utilización de un LLM privado - Técnicas de recuperación de información con generación de lenguaje para la mejora la generación de contenido. Demo: - Implementación de un LLM en AWS con ejemplos de código y resultados. -Integración de un modelo de Hugging Face en AWS para un LLM privado. - Mostrar RAG impacta positivamente en la calidad y relevancia de las respuestas generadas. Objetivos de la sesión: - Explorar la combinación de LLMs en AWS optimiza el rendimiento y la escalabilidad. - Uso de un LLM privado para mejorar personalización y seguridad. -Impacto de RAG en la mejora de la generación de texto para eficiencia de precision.', 'Sesion regular', 'Intermedio', 60, 11),
('Microsoft Fabric Onelake Shortcuts', 'En esta charla, exploraremos cómo los accesos directos de Microsoft OneLake están revolucionando la gestión de datos corporativos, permitiendo una integración sin precedentes entre plataformas como Azure y AWS. Profundizaremos en su capacidad para crear un lago de datos virtual unificado, simplificando enormemente la administración de permisos y mejorando la eficiencia al reducir la latencia en el manejo de datos.', 'Sesion regular', 'Intermedio', 60, 12),
('Registro', 'Proceso de registro en el evento', NULL, NULL, 15, 13),
('Bienvenida', 'Palabras de bienvenida por Carlos Lopez', NULL, NULL, 20, 13),
('Almuerzo', 'Almuerzo por cortesia de SQL Saturday', NULL, NULL, 60, 13),
('Coffee break', 'Coffee break por cortesia de EduKids', NULL, NULL, 10, 13),
('Sponsors', 'Mencion a nuestros sponsors por Hugo Estrada', NULL, NULL, 10, 13),
('Cloud Skills Challenge', 'Premiacion de ganadores del Cloud Skills Challenge por Geovani de Leon', NULL, NULL, 20, 4),
('Cierre', 'Palabras de cierre por Carlos Lopez', NULL, NULL, 20, 13),
('Microsoft Guatemala', 'TBD', 'Sesion corta', 'Avanzado', 60, 14);
GO